# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            files: ^.*\.cmake|CMakeLists\.txt$
          - id: end-of-file-fixer
            files: ^.*\.cmake|CMakeLists\.txt$
            
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v14.0.6
      hooks:
          - id: clang-format
            types_or: [c++, c]
